message = input("Hello, Enter your name, Sir : ")
print(message + ", Welcome to Sintcare, python training course.")
hobby = input("What is your hobby? Sir : ")
print("Great! " + hobby + " is a fantastic one.")
defence = input("Which one is the most you like? : ")
print(defence + "!, I know it. But not properly.")
cow = input("How long have you been playing for " + defence + "? : ")
print("Wow, it is a long journey.")
cat = input("What is " + defence + " and how is it played? : ")
print("According to your explanation, " + defence + " is a type of online game which requires 10 players.")
